# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lcMrvgXtDrUN0ex4hkPL3AUAQZqmAnre
"""

# 這是 prize 套件的初始化檔案