# -*- coding: utf-8 -*-
"""exlotto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gy5IQMlx-JsNBYR1sSFIJOToPGTKu0Gp
"""

import random

def lotto(n, m):
    numbers = list(range(1, n + 1))
    result = []

    for _ in range(m):
        pick = random.choice(numbers)
        numbers.remove(pick)
        result.append(pick)

    return result

