# -*- coding: utf-8 -*-
"""exreciept.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TklWBR7YMcSwO_FR6_5fAYV8PL3Vf1tx
"""

import random

def receipt():
    number = ''
    for _ in range(8):
        digit = str(random.randint(0, 9))
        number += digit
    return number

